#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080

# Configure Nginx master process to run as nginx user instead of root
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/user root;/user nginx;/g' /etc/nginx/nginx.conf

# Configure default site to listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Fix file permissions so nginx user can access Nginx files
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /etc/nginx

# Restart Nginx service as nginx user
su -c "service nginx restart" nginx
