#!/usr/bin/env bash
# Configures Nginx to include a custom HTTP header X-Served-By with the server hostname

# Update packages and install Nginx
sudo apt-get update -y
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y nginx

# Add X-Served-By header in http block of nginx.conf using Nginx's $hostname variable
if ! grep -q "X-Served-By" /etc/nginx/nginx.conf; then
    sudo sed -i '/http {/a \    add_header X-Served-By "$hostname";' /etc/nginx/nginx.conf
fi

# Test configuration and restart Nginx
sudo nginx -t && sudo service nginx restart
