#!/usr/bin/env bash
# Script that installs and configures an Nginx web server

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
